Setup
anyepeter/hello-rails-react pull request #1
Opened 2023-04-05 21:33 UTC by anyepeter

2023-04-05 23:03 UTC, MahmoudBakr23 requested changes
Hello @anyepeter 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Great job so far on the back end creating the Message model, versioning the API, setting up the controller's method, and routes
- Well done with the front end installing the using redux toolkit to handle the state and data fetched from the API, and using react hooks correctly such as `useEffect` hook
- Descriptive PR
- Correct Linters

However, there is always room for improvement.

> I'd like to remind you that your long hours of work are appreciated. However, the code review process is for improving your code, not criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 23:03 UTC, MahmoudBakr23 commented on README.md
> +  <h3><b>Budget-App README</b></h3>
- [ ] Please change the app's name because every app has its own unique README file

2023-04-05 23:03 UTC, MahmoudBakr23 commented on README.md
> +Here is the link to the video presentation of the [project](https://www.loom.com/share/1e0b6607108c4e4fb2f9d6ea54bd8cb7)
- [ ] Kindly change/delete the links to the live link and presentation video because they don't relate to this app

2023-04-05 23:03 UTC, MahmoudBakr23 commented on README.md
> +- Huge appriciation to Gregoire Vella for providing design system guidelines since this project is built upon thatopment.
- [ ] Please re-write the acknowledgements section as it does not relate to this project

2023-04-05 23:03 UTC, MahmoudBakr23 commented on README.md
> +This project is [MIT](./https://github.com/anyepeter/rails-budget/blob/develop/LICENSE) licensed.
- [ ] Please fix the MIT link for a professional README file

2023-04-05 23:03 UTC, MahmoudBakr23 commented on db/seeds.rb
> +#   Character.create(name: "Luke", movie: movies.first)
- [ ] I think you might have missed creating the 5 different messages in the database seeds so that they're generated randomly by the controller you created and then displayed on the front end. As you mentioned [here](https://github.com/anyepeter/hello-rails-react/pull/1#:~:text=Create%20a%20table%20for%20storing%20your%20messages%20and%20create%205%20different%20greetings.), please do so 😄

2023-04-07 14:49 UTC, andersonlebon requested changes
## Hi @anyepeter 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## To highlight :champagne: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 14:49 UTC, andersonlebon commented on README.md
> +  <h3><b>Budget-App README</b></h3>
- [ ] Kindly make sure your app has its own name related to the content as the previous reviewer requested.

## OPTIONAL]
- [ ] Kindly make sure next time you use the correct flow in the requirements of this project it's required to use gitflow, and for gitflow on solo projects the PR should be open from the feature branch to the dev branch

2023-04-07 15:27 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 21:43 UTC, merged